<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * FasilitasSeeder — Data riil fasilitas umum Kota Medan.
 * Puskesmas: koordinat dari data OSM/CSV lapangan.
 * Damkar & Taman: koordinat dari data publik.
 *
 * kecamatan_id mapping (sesuai urutan KecamatanSeeder):
 *  1=Medan Kota, 2=Medan Barat, 3=Medan Timur, 4=Medan Petisah,
 *  5=Medan Sunggal, 6=Medan Helvetia, 7=Medan Baru, 8=Medan Polonia,
 *  9=Medan Maimun, 10=Medan Selayang, 11=Medan Tuntungan, 12=Medan Johor,
 *  13=Medan Amplas, 14=Medan Denai, 15=Medan Area, 16=Medan Perjuangan,
 *  17=Medan Tembung, 18=Medan Deli, 19=Medan Labuhan, 20=Medan Marelan,
 *  21=Medan Belawan
 */
class FasilitasSeeder extends Seeder
{
    public function run()
    {
        $this->db->table('fasilitas')->truncate();

        $data = [
            // ── PUSKESMAS ──────────────────────────────────────────────
            [
                'nama'            => 'Puskesmas Padang Bulan',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Jamin Ginting, Padang Bulan, Medan Baru',
                'kecamatan_id'    => 7,
                'latitude'        => 3.56145,
                'longitude'       => 98.66212,
                'deskripsi'       => 'Puskesmas pelayanan kesehatan dasar masyarakat Kelurahan Padang Bulan dan sekitarnya. Melayani rawat jalan, KIA, imunisasi, dan program KB.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–16.00',
                'telepon'         => '(061) 8211340',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Pasar Petisah',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Nibung II, Petisah Tengah, Medan Petisah',
                'kecamatan_id'    => 4,
                'latitude'        => 3.59001,
                'longitude'       => 98.66592,
                'deskripsi'       => 'Puskesmas dengan layanan poli umum, poli gigi, laboratorium sederhana, dan posyandu aktif setiap bulan.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 4538221',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Tanjung Sari',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Kenanga Raya, Tanjung Sari, Medan Selayang',
                'kecamatan_id'    => 10,
                'latitude'        => 3.56157,
                'longitude'       => 98.63674,
                'deskripsi'       => 'Puskesmas wilayah Medan Selayang melayani masyarakat kelurahan Tanjung Sari dengan berbagai program kesehatan promotif dan preventif.',
                'jam_operasional' => 'Senin–Sabtu: 08.00–15.00',
                'telepon'         => '(061) 8225670',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Glugur Kota',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. K.L. Yos Sudarso, Glugur Kota, Medan Barat',
                'kecamatan_id'    => 2,
                'latitude'        => 3.60749,
                'longitude'       => 98.67390,
                'deskripsi'       => 'Puskesmas Glugur Kota merupakan fasilitas kesehatan tingkat pertama di kawasan Medan Barat, melayani program kesehatan ibu dan anak.',
                'jam_operasional' => 'Senin–Jumat: 07.30–16.00, Sabtu: 07.30–12.00',
                'telepon'         => '(061) 6610234',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Glugur Darat',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Pasar Inpres Pendidikan, Glugur Darat I, Medan Timur',
                'kecamatan_id'    => 3,
                'latitude'        => 3.61551,
                'longitude'       => 98.68219,
                'deskripsi'       => 'Puskesmas Glugur Darat melayani masyarakat Medan Timur dengan layanan rawat jalan, MTBS, dan program pencegahan penyakit menular.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 7364412',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Kampung Baru',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Brigjen Katamso, Kampung Baru, Medan Maimun',
                'kecamatan_id'    => 9,
                'latitude'        => 3.55191,
                'longitude'       => 98.68713,
                'deskripsi'       => 'Puskesmas di kawasan Medan Maimun yang melayani kunjungan rawat jalan dan program prolanis untuk penderita hipertensi dan diabetes.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 4512890',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Helvetia',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Kemuning XII, Helvetia, Medan Helvetia',
                'kecamatan_id'    => 6,
                'latitude'        => 3.61277,
                'longitude'       => 98.63267,
                'deskripsi'       => 'Puskesmas Helvetia dengan fasilitas lengkap meliputi poli umum, poli gigi, KIA/KB, laboratorium, dan apotek.',
                'jam_operasional' => 'Senin–Jumat: 07.30–16.00, Sabtu: 07.30–12.00',
                'telepon'         => '(061) 8465321',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Tuntungan',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Pinus 2, Mangga, Medan Tuntungan',
                'kecamatan_id'    => 11,
                'latitude'        => 3.51434,
                'longitude'       => 98.63149,
                'deskripsi'       => 'Puskesmas melayani masyarakat Medan Tuntungan di wilayah perbatasan Kota Medan. Program unggulan: kesehatan lingkungan dan gizi masyarakat.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 8361227',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Johor',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Sempurna, Kedai Durian, Medan Johor',
                'kecamatan_id'    => 12,
                'latitude'        => 3.52035,
                'longitude'       => 98.68404,
                'deskripsi'       => 'Puskesmas Johor memberikan layanan kesehatan komprehensif bagi masyarakat Kecamatan Medan Johor dan sekitarnya.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–15.30',
                'telepon'         => '(061) 7877541',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Harjosari',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Pertiwi, Harjosari I, Medan Amplas',
                'kecamatan_id'    => 13,
                'latitude'        => 3.54587,
                'longitude'       => 98.71220,
                'deskripsi'       => 'Puskesmas Harjosari melayani masyarakat Medan Amplas dan Medan Denai bagian selatan dengan berbagai program kesehatan dasar.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 7872203',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Denai',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Gang Damai, Denai, Medan Denai',
                'kecamatan_id'    => 14,
                'latitude'        => 3.57173,
                'longitude'       => 98.72695,
                'deskripsi'       => 'Puskesmas Denai dengan layanan poli umum, poli gigi, KIA, imunisasi balita, dan klinik sanitasi.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 7335120',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Kota Bangun',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. K.L. Yos Sudarso, Kota Bangun, Medan Deli',
                'kecamatan_id'    => 18,
                'latitude'        => 3.67749,
                'longitude'       => 98.66483,
                'deskripsi'       => 'Puskesmas Kota Bangun melayani masyarakat kawasan Medan Deli bagian utara, dekat dengan kawasan industri Belawan.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 6853310',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Belawan',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Veteran, Belawan II, Medan Belawan',
                'kecamatan_id'    => 21,
                'latitude'        => 3.77923,
                'longitude'       => 98.68220,
                'deskripsi'       => 'Puskesmas Belawan melayani masyarakat pelabuhan dan sekitarnya dengan program kesehatan lingkungan dan sanitasi pelabuhan.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 6941002',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Puskesmas Marelan',
                'jenis'           => 'puskesmas',
                'alamat'          => 'Jl. Marelan Raya, Rengas Pulau, Medan Marelan',
                'kecamatan_id'    => 20,
                'latitude'        => 3.69824,
                'longitude'       => 98.65124,
                'deskripsi'       => 'Puskesmas Marelan melayani masyarakat Kecamatan Medan Marelan dengan program kesehatan ibu, anak, dan lansia.',
                'jam_operasional' => 'Senin–Sabtu: 07.30–14.00',
                'telepon'         => '(061) 6851765',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Puskesmas_Karang_Anyar.jpg/640px-Puskesmas_Karang_Anyar.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],

            // ── PEMADAM KEBAKARAN ──────────────────────────────────────
            [
                'nama'            => 'Dinas Pemadam Kebakaran Kota Medan',
                'jenis'           => 'damkar',
                'alamat'          => 'Jl. Kapten Maulana Lubis No. 2, Petisah Tengah, Medan Petisah',
                'kecamatan_id'    => 4,
                'latitude'        => 3.59410,
                'longitude'       => 98.67413,
                'deskripsi'       => 'Kantor pusat Dinas Pemadam Kebakaran Kota Medan. Beroperasi 24 jam dengan armada lengkap untuk penanganan kebakaran dan penyelamatan.',
                'jam_operasional' => '24 Jam (Siaga Penuh)',
                'telepon'         => '113 / (061) 4514969',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg/640px-Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'UPT Damkar Medan Selatan',
                'jenis'           => 'damkar',
                'alamat'          => 'Jl. Letda Sujono, Harjosari, Medan Amplas',
                'kecamatan_id'    => 13,
                'latitude'        => 3.54600,
                'longitude'       => 98.71350,
                'deskripsi'       => 'Unit Pelaksana Teknis Damkar wilayah Medan Selatan mencakup Kecamatan Medan Amplas, Medan Johor, dan Medan Denai.',
                'jam_operasional' => '24 Jam (Siaga Penuh)',
                'telepon'         => '113 / (061) 7887234',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg/640px-Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Pos Damkar Medan Utara',
                'jenis'           => 'damkar',
                'alamat'          => 'Jl. Yos Sudarso, Kota Bangun, Medan Deli',
                'kecamatan_id'    => 18,
                'latitude'        => 3.67748,
                'longitude'       => 98.66490,
                'deskripsi'       => 'Pos pemadam kebakaran yang melayani wilayah Medan Utara, Medan Deli, Medan Labuhan, Medan Belawan, dan sekitarnya.',
                'jam_operasional' => '24 Jam (Siaga Penuh)',
                'telepon'         => '113 / (061) 6853012',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg/640px-Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Pos Damkar Medan Barat',
                'jenis'           => 'damkar',
                'alamat'          => 'Jl. Putri Hijau, Kesawan, Medan Barat',
                'kecamatan_id'    => 2,
                'latitude'        => 3.61800,
                'longitude'       => 98.67100,
                'deskripsi'       => 'Pos pemadam kebakaran kawasan Medan Barat dan Medan Helvetia. Dilengkapi unit penyelamatan dan ambulance darurat.',
                'jam_operasional' => '24 Jam (Siaga Penuh)',
                'telepon'         => '113 / (061) 6613450',
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg/640px-Mobil_Dinas_Pemadam_Kebakaran_DKI_Jakarta.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],

            // ── TAMAN KOTA ─────────────────────────────────────────────
            [
                'nama'            => 'Lapangan Merdeka Medan',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Balai Kota No. 1, Kesawan, Medan Barat',
                'kecamatan_id'    => 2,
                'latitude'        => 3.59480,
                'longitude'       => 98.67330,
                'deskripsi'       => 'Lapangan Merdeka adalah ruang terbuka hijau ikonik Kota Medan sejak era kolonial. Digunakan untuk olahraga, upacara, dan kegiatan publik warga kota.',
                'jam_operasional' => 'Setiap hari: 05.00–22.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Lapangan_Merdeka_Medan.jpg/640px-Lapangan_Merdeka_Medan.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Taman Ahmad Yani',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Pemuda, Kesawan, Medan Barat',
                'kecamatan_id'    => 2,
                'latitude'        => 3.59630,
                'longitude'       => 98.67750,
                'deskripsi'       => 'Taman kota dengan RTH aktif, dilengkapi fasilitas jogging track, bangku taman, dan area bermain anak. Ramai dikunjungi warga pada pagi dan sore hari.',
                'jam_operasional' => 'Setiap hari: 06.00–21.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Taman_Suropati_Menteng.jpg/640px-Taman_Suropati_Menteng.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Taman Bunga Medan (Simalingkar)',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Bunga Raya, Simalingkar B, Medan Tuntungan',
                'kecamatan_id'    => 11,
                'latitude'        => 3.51140,
                'longitude'       => 98.64240,
                'deskripsi'       => 'Taman kota asri di kawasan Simalingkar dengan koleksi tanaman hias dan pohon pelindung. Cocok untuk rekreasi keluarga dan bersepeda.',
                'jam_operasional' => 'Setiap hari: 06.00–18.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Taman_Suropati_Menteng.jpg/640px-Taman_Suropati_Menteng.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Taman Kota Sei Sikambing',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Kapten Muslim, Sei Sikambing C II, Medan Helvetia',
                'kecamatan_id'    => 6,
                'latitude'        => 3.60320,
                'longitude'       => 98.64100,
                'deskripsi'       => 'Taman kota dengan area hijau yang luas, dilengkapi jogging track dan tempat duduk. Menjadi paru-paru kota di kawasan padat Medan Helvetia.',
                'jam_operasional' => 'Setiap hari: 05.30–21.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Taman_Suropati_Menteng.jpg/640px-Taman_Suropati_Menteng.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Taman Teladan',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Teladan Barat, Teladan Barat, Medan Kota',
                'kecamatan_id'    => 1,
                'latitude'        => 3.56370,
                'longitude'       => 98.69390,
                'deskripsi'       => 'Taman Teladan adalah ruang terbuka hijau di kawasan Medan Kota yang populer untuk olahraga pagi dan sore hari warga sekitar.',
                'jam_operasional' => 'Setiap hari: 05.00–21.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Taman_Suropati_Menteng.jpg/640px-Taman_Suropati_Menteng.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
            [
                'nama'            => 'Taman Beringin',
                'jenis'           => 'taman',
                'alamat'          => 'Jl. Jend. A.H. Nasution, Pangkalan Masyhur, Medan Johor',
                'kecamatan_id'    => 12,
                'latitude'        => 3.52220,
                'longitude'       => 98.67660,
                'deskripsi'       => 'Taman Beringin dengan pohon-pohon besar berusia puluhan tahun. Menjadi landmark RTH kawasan Medan Johor dan sekitarnya.',
                'jam_operasional' => 'Setiap hari: 06.00–20.00',
                'telepon'         => null,
                'foto_url'        => 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Taman_Suropati_Menteng.jpg/640px-Taman_Suropati_Menteng.jpg',
                'created_at'      => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('fasilitas')->insertBatch($data);

        echo "✅ " . count($data) . " data fasilitas Kota Medan berhasil ditambahkan.\n";
        echo "   - Puskesmas : 14\n";
        echo "   - Damkar    : 4\n";
        echo "   - Taman     : 6\n";
    }
}